
services:
  db:
    container_name: mydb
    image: mariadb:lts
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: mydb
      MARIADB_USER: ${DB_LOGIN}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

    ports:
      - "${DB_PORT}:${DB_PORT}"

    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 10

#  app:
#    container_name: myapp
#    build: .
#    env_file:
#      - .env
#    environment:
#      DB_URL: db:3306/mydb
#      REDIS_HOST: redis
#    depends_on:
#      db:
#        condition: service_healthy
#    ports:
#      - "8081:8081"

  redis:
    container_name: redis
    image: redis:8
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    volumes:
      - redis-data:/data

  minio:
    # Используемый образ Docker. Рекомендуется указывать конкретный тег для стабильности.
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: s3
    command: server /data --address ":9010" --console-address ":9011"
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123

    ports:
      - "9010:9010" # API port
      - "9011:9011" # Console port
    volumes:
      - minio-data:/data
    deploy:
      resources:
        limits:
          memory: 1024m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"



volumes:
  db_data:
  redis-data:
  minio-data:
