
services:
  db:
    container_name: mydb
    image: mariadb:lts
    environment:
      MARIADB_NAME: mydb
      MARIADB_USER: ${DB_LOGIN}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: myapp
    build: .
    env_file:
      - .env
    environment:
      DB_URL: db:3306/mydb
    depends_on:
      - db
    ports:
      - "8081:8081"

  redis:
    container_name: redis
    image: redis:lts
    ports:
      - ${REDIS_PORT}
    environment:
      REDIS_HOST: redis


    # minio
    # redis



volumes:
  dbdata:
