
services:
  db:
    image: postgres:16
    container_name: mydb
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  app:
    container_name: myapp
    build: .
    env_file:
      - .env
    environment:
      DB_URL: db:5432/cloud_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"

  redis:
    container_name: redis
    image: redis:8
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

  minio:
    # Используемый образ Docker. Рекомендуется указывать конкретный тег для стабильности.
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: s3
    command: server /data --address ":9010" --console-address ":9011"
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: ${MINIO_PASSWORD}

    ports:
      - "9010:9010" # API port
      - "9011:9011" # Console port
    volumes:
      - minio-data:/data
    deploy:
      resources:
        limits:
          memory: 1024m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"



volumes:
  pgdata:
  redis-data:
  minio-data:
