server:
  port: 8081
  servlet:
    session:
      timeout: 2d # default 30m
spring:
  session:
    store-type: redis

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:${DB_SQL_NAME}://${DB_URL}
#    url: jdbc:mariadb://db:3306/mydb
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 1
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

    # --- Конфигурация Spring Cloud AWS ---
#    cloud:
#      aws:
#        credentials:
#          # Используем ключи из docker-compose.yml
#          access-key: ${MINIO_ACCESS_KEY:admin}
#          secret-key: ${MINIO_SECRET_KEY:admin123}
#        s3:
#          # Указываем наш API-эндпоинт MinIO
#          endpoint: ${MINIO_ENDPOINT:http://localhost:9010}
#          # КРИТИЧЕСКИ ВАЖНО для MinIO: использовать доступ в стиле path-style
#          path-style-access-enabled: true
#        region:
#          # Регион для MinIO не важен, но обязателен для SDK. us-east-1.
#          static: us-east-1

  minio:
    endpoint: http://localhost:9010
    access-key: admin
    secret-key: admin123
    bucket: user-bucket


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

