spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_db
  minio:
    endpoint: http://localhost:9010
  data:
    redis:
      host: localhost
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false